# Generated by Django 4.2.7 on 2023-11-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bisWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidboss',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bisWeb.raid'),
        ),
    ]
