# Generated by Django 4.2.7 on 2023-11-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisWeb', '0003_alter_bossitem_boss_alter_player_bisitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidboss',
            name='raid',
        ),
        migrations.DeleteModel(
            name='Raid',
        ),
    ]
