# Generated by Django 4.2.7 on 2023-11-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bisWeb', '0004_remove_raidboss_raid_delete_raid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPicked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemLevel', models.CharField(max_length=64)),
                ('bossItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bisWeb.bossitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bisWeb.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='pickedItems',
            field=models.ManyToManyField(related_name='playersPickedItems', through='bisWeb.ItemPicked', to='bisWeb.bossitem'),
        ),
    ]
