# Generated by Django 4.2.7 on 2023-11-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisWeb', '0005_itempicked_player_pickeditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pickedItems',
        ),
    ]
